Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "miniupnpc", source_glob="*.c", in_bin=False
)

if "gcc" in env["TOOLS"]:
    env.Append(
        CCFLAGS=[
            "-Wno-unused-value",
        ]
    )

if dev.is_win32():
    env.Append(CPPDEFINES=["MINIUPNP_STATICLIB", "WIN32"])

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return("ret")
