Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "bzip2", source_glob="*.c", in_bin=False
)

if "gcc" in env["TOOLS"]:
    env.Append(CCFLAGS=["-Wno-implicit-fallthrough"])

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return("ret")
