Import("dev source_path")

env, target, sources = dev.prepare_build(
    source_path, "natpmp", source_glob="*.c", in_bin=False
)

if dev.is_win32():
    env.Append(
        CPPDEFINES=[
            'errno="WSAGetLastError()"',
            "STATICLIB",
            "NATPMP_STATICLIB",
            "WIN32",
        ]
    )

ret = dev.build_lib(env, target, sources, dev.c_lib)
Return("ret")
