<dl style="margin-left: 40px;">
  <dt>Download</dt>
  <dd>Adds the selected file(s) or director(ies) to the Download Queue. They will
      be downloaded to the <a href="settings_downloads.html#defdwnlddir">Default
  	  download directory</a>.</dd>	  
  <dt>Download to...</dt>
  <dd>Adds the selected file(s) or director(ies) to the Download Queue. The download
  	  target can be selected using the submenu elements : either a predefined place
  	  from the <a href="settings_favoritedirs.html">Download Favorites</a> or any other
  	  folder specified using the <i>Browse...</i> submenu.</dd>	  
</dl>