<dl style="margin-left: 40px;">
  <dt>Search for &quot;text&quot;</dt>
  <dd>Will open a new <a href="window_search.html">Search window</a> to search
  	  hubs for selected text or the text under the cursor.</dd>
  <dt>Search by TTH</dt>
  <dd>If a selection is detected as a Tiger Tree Hash this will open a new 
  	  <a href="window_search.html">Search window</a> to search hubs for the selected
  	  or under cursor TTH value.</dd>
</dl>
