<dl style="margin-left: 40px;">
	<dt>Get file list</dt>
	<dd>Download the file list of the selected users.</dd>
	<dt>Browse file list</dt>
	<dd>Download only the required pieces of the file lists of the selected users in form of a partial file list. Note that you may not able to fully exploit certain file list functions in a partial list window until you get the whole list using the "Download full list" button.</dd>
	<dt>Match queue</dt>
	<dd>Matches the files in your download queue to the file lists of the selected
	users. 2 files are considered to be the same if their TTH is the same. If matches are found in one user's file list,
	she will be added as a source for the relevant downloads.</dd>
	<dt>Send private message</dt>
	<dd>Open <placeholder><a href="window_pm.html">Private Message</a></placeholder> windows to
	chat privately with the selected users.</dd>
	<dt>Send public message</dt>
	<dd>Prepend selected user nicks to public chat message input. Use this to address your message
	to specific user or multiple users. Your message will be sent as public message as stated in
	input field.</dd>
	<dt>Grant extra slot</dt>
	<dd>In addition to your regular upload slots, an extra upload slot will be given to the
	selected users until the end of the current DC++ session.</dd>
	<dt>Remove user from queue</dt>
	<dd>Remove the selected users from the source list of all queued files. Pending file list
	requests will be removed as well.</dd>
	<dt>Ignore chat</dt>
	<dd>Add user matching definitions (or modify existing ones, if possible) to ignore chat
	messages from the selected users.</dd>
	<dt>Un-ignore chat</dt>
	<dd>Add user matching definitions (or modify existing ones, if possible) to stop ignoring chat
	messages from the selected users.</dd>
	<dt>Copy user information</dt>
	<dd>Copy a few lines containing user information to the clipboard. The data may include: the
	user's nick(s), her hub address(es), her IP, country, email, CID (not exhaustive). When
	multiple users are selected, each user information blob is separated with a blank line.</dd>
</dl>

