<dl style="margin-left: 40px;">
  <dt>Search for alternates</dt>
  <dd>Will open a new <a href="window_search.html">Search window</a> to search
  	  for alternate sources for the selected file.</dd>
  <dt>Copy magnet link to clipboard</dt>
  <dd>Will copy the file's <a href="https://en.wikipedia.org/wiki/Magnet_URI_scheme"
  	  target="_blank" class="external">magnet link</a> to the clipboard.</dd>
</dl>
