<dl style="margin-left: 40px;">
  <dt>Open</dt>
  <dd>Opens the file with its respective external viewer software. You should have
  	  the appropriate viewer / player software installed and correctly registered to be able
  	  to open the file.</dd>	  
  <dt>Open folder</dt>
  <dd>Opens the selected folder (or the folder containing the selected file) in
  	  Windows Explorer.</dd>	  
  <dt>Shell menu</dt>
  <dd>Opens the Windows shell menu as submenu items. This menu contains the same 
  	  items as in the context menu of Windows Explorer. Note that the submenu elements will be
  	  loaded the time when it is opened. If you have large number of context menu items
  	  registered with Windows it may take a few seconds to show the full menu.</dd>	  
</dl>
