<p>Above the basic text selection and copy to clipboard commands the following search related commands will appear in the menu:</p>
<dl style="margin-left: 40px;">
  <dt>Find...</dt>
  <dd>This will show an input box for textual searches within the chat content. Searches will be performed from the bottom to the top.</dd>
  <dt>Find Next</dt>
  <dd>This will repeat the last textual search within the chat content in upward direction.</dd>
</dl>
