  	  <p>This function is useful for previewing small text based info
  	  files as they may contain more information about other files in the same folder.
  	  Note that only plain text files will be shown correctly. For files of other
  	  format you must download and open them with their respective viewer application. 
  	  You can open downloaded files from the
  	  <a href="window_finished_downloads.html">Finished downloads</a> window using
  	  the Open menu command.</p>