	<ul>
		<li>
		"Add" displays a file selection dialog to install a new plugin.
		</li>
		<li>
		"Configure" opens the <placeholder><a href="settings_plugins.html">Plugins</a></placeholder> configuration page.
		</li>
		<li>
		Installed plugins are listed below. They can be selectively enabled or disabled. A "Configure" command is also available for each of them (the behavior of which is plugin-dependant). Plugins are also allowed to add additional commands in that sub-menu.
		</li>
	</ul>
