  <dt>Status</dt>
  <dd>Connection status of the hub. Possible indicators: 
  	<ul>
  		<li><img src="HubOn.ico" width="16" height="16" alt="Hub"/> Connected - Hub is connected, hub window is open.</li>
  		<li><img src="HubOff.ico" width="16" height="16" alt="Hub"/> Disconnected - Hub is disconnected, but the hub window is still open.</li>
  		<li>Empty - No window opened for the hub.</li>
  	</ul>
  </dd>
  <dt>Name</dt>
  <dd>The name of the hub.</dd>
  <dt>Description</dt>
  <dd>The hub's description.</dd>
